
language: java

services:
  - docker

before_install:
- docker pull adoptopenjdk/openjdk11:jdk-11.0.3.7


script:
- docker run --rm -it -v $TRAVIS_BUILD_DIR/java:/grpc-example-java -w /grpc-example-java lukaswoodtli/grpc-example:latest ./gradlew
- docker run --rm -it -v $TRAVIS_BUILD_DIR:/grpc-example -w /grpc-example/cpp lukaswoodtli/grpc-example:latest "cmake -S . -B build && cmake --build build"
